# notice that this is an example config file and that keys and id's are no
# longer valid
endpoint_url='https://minio.dive.edito.eu/'
bucket=''
aws_access_key_id=''
aws_secret_access_key=''
aws_session_token=''